Own/urls.py
from django.contrib import admin
from django.urls import path,include
from logon import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('special',views.special,name='special'),
    path('logon',include('logon.urls')),
    path('logout',views.user_logout,name='logout'),
]

logon/urls.py
from django.conf.urls import url
from django.urls import path
from logon import views

app_name = 'logon'

urlpatterns=[
    path('register',views.register,name='register'),
    path('user_login',views.user_login,name='user_login'),
]

logon/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site=models.URLField(blank=True)

    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

logon/forms.py
from django import forms

from logon.models import UserProfileInfo

from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

logon/views.py
from django.shortcuts import render

from logon.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout

from django.http import HttpResponseRedirect,HttpResponse

from django.urls import reverse

from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,'logon/index.html')

@login_required
def special(request):
    return HttpResponse("you are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                print("Found it")
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request,'logon/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Your account was Inactive')
        else:
            print("Someone tried to login and failed")
            print("They used username :{} and password :{}".format(username,password))
            return HttpResponse("Invalid login Details")
    else:
        return render(request,'logon/login.html',{})

templates/logon/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          <ul class="nav navbar-nav">
              {# Django Home Link/ Admin Link / Register Link #}
              <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
              <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
              <li><a class="navbar-link" href="{% url 'logon:register' %}">Register</a></li>
              {# some logic on what to display for last item #}
              {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
              {% else %}
                <li><a class="navbar-link" href="{% url 'logon:user_login' %}">Login</a></li>
              {% endif %}
          </ul>
      </div>
  </nav>
  <div class="container">
      {% block content %}
      {% endblock %}
  </div>  
</body>
</html>

templates/logon/index.html
{% extends 'logon/base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Welcome to Mypage</h1>
        {% if user.is_authenticated %}
            <h2> Hello {{user.username}}</h2>
        {% else %}
            <h2> Go for Login or Registration </h2>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/logon/login.html
{% extends 'logon/base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Login here:</h1>
        <form method="POST" action="{% url 'logon:user_login' %}">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username">
            <label for="password">Password:</label>
            <input type="text" name="password" placeholder="Password">
            <input type="submit" name="" value="Login">
        </form>"
    </div>
</div>
{% endblock %}

templates/logon/registration.html
{% extends 'logon/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
            <h1> Thankyou for Registering! </h1>
        {% else %}
            <h1>Register here</h1>
            <h3> Just fill out the form </h3>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}